### ISSUE TITLE
What is the maximum download speed/upload? 

### ISSUE THREAD

**Issue by foremtehan** [tginfo/Telegram-Limits#38]
I'm sure there is a limit for upload and download in telegram.

**Comment by Sominemo** [comment]
We had a discussion about this and concluded we are **not going** to add this because:

- Upload/download speed is a rapidly changing value which depends on a plenty of factors like your own internet speed, connection quality, network load, your ISP limitations, proxy etc.
- There's no clear server-side limit on Telegram servers

Thank you for taking your time.
